subsystems:
  drivetrain:
    implemented: true
    motors:
      leftMain:
        motorType: TalonFX
        motorName: leftMain
        id: 1
        invertMotor: true
      rightMain:
        motorType: TalonFX
        motorName: rightMain
        id: 2
        invertMotor: false
      leftFollower:
        motorType: TalonFX
        motorName: leftFollower
        id: -1
        invertMotor: false
      leftFollowerTwo:
        motorType: TalonFX
        motorName: leftFollowerTwo
        id: -1
        invertMotor: false
      rightFollower:
        motorType: TalonFX
        motorName: rightFollower
        id: -1
        invertMotor: false
      rightFollowerTwo:
        motorType: TalonFX
        motorName: rightFollowerTwo
        id: -1
        invertMotor: false
    pidConfig:
      slot0:
        kP: 0.1 # 0.18
        kI: 0.0001 # 0.018
        kD: 4.0 # 3.6
        kF: 0.0475813
    constants:
      maxVelTicks100ms: 40275.7
      encPPR: 22220.8
      openLoopRampRate: 0.8
      isSwerve: 0
      isCTRSwerve: 0
      maxRotVel: 7.2
      trackWidth: 21.5
      wheelbaseLength: 21.5 #inches
      wheelDiameter: 6.32
      kTrackScrubFactor: 1.0
      maxVelOpenLoop: 2.5 # meters/s
      maxVelPathFollowing: 2.2 # meters/s
      maxRotVelClosedLoop: 2
      maxAccel: 2.54 # meters/s^2
      currentLimit: 30
      isDemoMode: 1
infrastructure:
  canBusName: rio
  # power distribution
  pdId: 0
  pdIsRev: false
  # pneumatics control
  compressorEnabled: false
  pcmIsRev: false
  pcmId: -1
  # pigeon
  pigeonId: 3
  isPigeon2: false
inputHandler: drivercentric # demo
constants:
  # drivetrain misc
  maxAllowablePoseError: 0.1
  minAllowablePoseError: 0.025
  ## Logging ##
  logRobot: 0
  logDrivetrain: 0 # 0 or 1
  configStatusFrames: 0 # 0 or 1
  verbose: 0 # 0 or 1
  ## General ##
  EnableBucketTuning: 1
  teleopFieldCentric: 1 # 0 or 1
  kLooperDt: .035 # seconds
  resetFactoryDefaults: 0 # whether motors get reset to factory default
  rotationToleranceClosedLoop: 0.5
  hasCanivore: 1
