subsystems:
  drivetrain:
    implemented: true
    motors:
      leftMain:
        motorType: TalonFX
        motorName: leftMain
        id: 17
        invertMotor: true
      rightMain:
        motorType: TalonFX
        motorName: rightMain
        id: 14
        invertMotor: false
      # motors i won't remove because i'm too scared something will break
      leftFollower:
        motorType: TalonFX
        motorName: leftFollower
        id: -1
        invertMotor: false
      leftFollowerTwo:
        motorType: TalonFX
        motorName: leftFollowerTwo
        id: -1
        invertMotor: false
      rightFollower:
        motorType: TalonFX
        motorName: rightFollower
        id: -1
        invertMotor: false
      rightFollowerTwo:
        motorType: TalonFX
        motorName: rightFollowerTwo
        id: -1
        invertMotor: false
    pidConfig:
      slot0:
        kP: 0.1 # 0.18
        kI: 0.0001 # 0.018
        kD: 4.0 # 3.6
        kF: 0.0475813
    constants:
      maxVelTicks100ms: 40275.7
      encPPR: 22220.8
      openLoopRampRate: 0.8
      isSwerve: 0
      isCTRSwerve: 0
      maxRotVelClosedLoop: 1
      maxRotVel: 7.2
      trackWidth: 21 #inches
      wheelbaseLength: 21.5 #inches
      wheelDiameter: 4
      kTrackScrubFactor: 1.0
      maxVelOpenLoop: 3 # meters/s
      maxVelPathFollowing: 2.2 # meters/s
      maxAccel: 2.54 # meters/s^ 2
      currentLimit: 40
      isDemoMode: 1
infrastructure:
  canBusName: rio
  # power distribution
  pdId: 0
  pdIsRev: false
  # pneumatics control
  compressorEnabled: false
  pcmIsRev: false
  pcmId: -1
  # pigeon
  pigeonId: 9
  isPigeon2: false
inputHandler: example # demo
constants:
  zeroingButton: 9 # channel of DIO port
  enableMusic: 0
  ## Drivetrain ##
  minAllowablePoseError: 0.025
  maxAllowablePoseError: 5
  soundOnConfig: 0 #If this is false, It will still beep on robot bootup.
  rotationToleranceClosedLoop: 0.5
  ## Logging ##
  logRobot: 1 # 0 or 1
  logDrivetrain: 1 # 0 or 1
  configStatusFrames: 0 # 0 or 1
  ## General ##
  usingVision: 0
  teleopFieldCentric: 1 # 0 or 1
  kLooperDt: .025 # seconds
  isProLicensed: 0
  hasCanivore: 1 # 0 or 1
  resetFactoryDefaults: 1 # whether motors get reset to factory default
