#TODO should probably either delete or fully revamp this class
subsystems:
  drivetrain:
    implemented: true
    falcons:
      BLAz: 7
      FRAz: 6
    canCoders:
      FLEnc: 9 #TODO check values
      FREnc: 12
      RLEnc: 17
      RREnc: 16
    invertMotor:
      - FLAz
      - FRAz
      - RLAz
      - RRAz
      - FRDr
      - RRDr
    invertCanCoder:
      - FREnc
      - BREnc
    swerveModules:
      modules:
        frontLeft:
          drive: FLDr
          azimuth: FLAz
          canCoder: FLEnc
          constants:
            encoderOffset: -2121
            invertSensorPhase: 1
        frontRight:
          drive: FRDr
          azimuth: FRAz
          canCoder: FREnc
          constants:
            encoderOffset: -1715
            invertSensorPhase: 1
    tankModules:
      modules:
        frontLeft:
          drive: FRAz
          azimuth: -1
          canCoder: FLEnc
          xCoord: 7.125
          yCoord: 11.375
          constants:
            encoderOffset: -0.34228515625
            couplingRatio: 3.576
            freeSpin12VRPS: 101
            invertSensorPhase: 1
        frontRight:
          drive: BLAz
          azimuth: -1
          canCoder: FREnc
          xCoord: 7.125
          yCoord: -11.375
          constants:
            encoderOffset: -0.014404296875
            couplingRatio: 3.579
            freeSpin12VRPS: 101
            invertSensorPhase: 1
      drivePID:
        slot0:
          kP: 0.1
          kI: 0.0001
          kD: 4.0
          kF: 0.0499
      azimuthPID:
        slot0:
          kP: 4.0 # 6.0
          kI: 0.0005
          kD: 30
          kF: 0
    constants:
      pigeonId: 13
      pigeonOnTalon: -1
      kP: 0.1 # 0.18 # TODO: tune PID, these are temporary PID values from Zeta
      kI: 0.0001 # 0.018
      kD: 4.0 # 3.6
      kF: 0.0475813
      iZone: 0
      currentFloorCheck: .12
      currentEpsilonCheck: .2
      rpmFloorCheck: 2000
      rpmEpsilonCheck: 60
      openLoopRampRate: 0.8
      isSwerve: 0
      encPPR: 21770
      azimuthEncPPR: 4096
      azimuthAllowableErrorTicks: 20
      azimuthHomeAdjustmentDegrees: 1
      isDemoMode: 0
pcm: 8
constants:
  maxVelTicks100ms: 12275.7 # ticks per 100ms TODO make into constant unique to each subsystem
  maxRotVel: 11.5
  maxVel: 120 # 160 # 240 # inches/s # 22560 native units ---30
  maxAccel: 100 # inches/s^2
  sensorPhase: 0
  kTrackScrubFactor: 1.0
  verbose: 0 # 0 or 1
  ## Logging ##
  ## General ##
  teleopFieldCentric: 1 # 0 or 1
  compressorEnabled: 0 # 0 or 1
  wheelDiameter: 4
  kLooperDt: .020 # seconds
  hasCanivore: 1
  rotationToleranceClosedLoop: 0.5
  logRobot: 1
  logDriveTrain: 1

infrastructure:
  canBusName: rio
  # power distribution
  pdId: 0
  pdIsRev: false
  # pneumatics control
  compressorEnabled: false
  pcmIsRev: false
  pcmId: 8
  # pigeon
  pigeonId: 9
  isPigeon2: false
